//
//  DetailScreenPresenter.swift
//  ListApp
//
//  Created by Nikita Omelchenko on 31.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private typealias Module = DetailScreenModule

extension Module {
    class Presenter: DetailScreenPresentationLogic {
        weak var viewController: DetailScreenDisplayLogic?

        func presentSomething(item: ResponseModels.CharacterModels.ResultModel) {
            let detailViewMdel: DetailScreenModule.Models.ViewModel = .init(
                id: item.id,
                name: item.name,
                status: item.status,
                species: item.species,
                type: item.type,
                gender: item.gender,
                origin: item.origin,
                location: item.location,
                image: item.image,
                url: item.url,
                created: item.created
            )

            viewController?.displaySomething(with: detailViewMdel)
        }
    }
}
