//
//  DetailScreenInteractor.swift
//  ListApp
//
//  Created by Nikita Omelchenko on 31.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private typealias Module = DetailScreenModule

extension Module {
    class Interactor: DetailScreenBusinessLogic, DetailScreenDataStore {
        var presenter: DetailScreenPresentationLogic?

        private let item: ResponseModels.CharacterModels.ResultModel

        init(item: ResponseModels.CharacterModels.ResultModel) {
            self.item = item
        }

        func fetchData() {
            presenter?.presentSomething(item: item)
        }
    }
}
