//
//  ListScreenPresenter.swift
//  ListApp
//
//  Created by Nikita Omelchenko on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListScreenPresentationLogic
{
  func presentSomething(response: ListScreen.Something.Response)
}

class ListScreenPresenter: ListScreenPresentationLogic
{
  weak var viewController: ListScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListScreen.Something.Response)
  {
    let viewModel = ListScreen.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
