//
//  ListScreenModels.swift
//  ListApp
//
//  Created by Nikita Omelchenko on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Extensions

private typealias Module = ListScreenModule

extension Module {
    enum Models {
        struct ViewModel: Identifiable {
            let id: Int
            let name: String
            let image: String
            let status: String
        }

        struct PageInfoModel {
            let nextPage: Int

            init(nexPageurl: String) {
                let numberOfPage = nexPageurl.components(separatedBy: "page=").last.flatMap(Int.init) ?? 1

                self.nextPage = numberOfPage
            }
        }

        struct DetailInfoModel {
            let id: Int
            let name: String
            let status: String
            let species: String
            let type: String
            let gender: String
            let origin: LinkedInfoModel
            let location: LinkedInfoModel
            let image: String
            let url: String
            let created: String
        }
    }
}
