//
//  ListScreenInteractor.swift
//  ListApp
//
//  Created by Nikita Omelchenko on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListScreenBusinessLogic
{
  func doSomething(request: ListScreen.Something.Request)
}

protocol ListScreenDataStore
{
  //var name: String { get set }
}

class ListScreenInteractor: ListScreenBusinessLogic, ListScreenDataStore
{
  var presenter: ListScreenPresentationLogic?
  var worker: ListScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListScreen.Something.Request)
  {
    worker = ListScreenWorker()
    worker?.doSomeWork()
    
    let response = ListScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
