//
//  ListScreenRouter.swift
//  ListApp
//
//  Created by Nikita Omelchenko on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private typealias Module = ListScreenModule

extension Module {
    class Router: NSObject, ListScreenRoutingLogic {
        weak var viewController: UIViewController?
        var dataStore: ListScreenDataStoreLogic?

        private let detailScreenAssembly: DetailAssemblyProtocol

        init(detailScreenAssembly: DetailAssemblyProtocol) {
            self.detailScreenAssembly = detailScreenAssembly
        }

        // MARK: Routing
        func pushDetailScreen(with row: Int) {
            guard let dataStore, let item = dataStore.dataSource[safe: row] else { return }

            let detailViewController = detailScreenAssembly.assemble(with: item)

            viewController?.navigationController?.pushViewController(detailViewController, animated: true)
        }
    }
}
